name: Distribution Builds

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
            jar: ['wilds-launcher-linux-x64-1.0.0.jar', 'wilds-launcher-windows-x64-1.0.0.jar', 'wilds-launcher-macos-x64-1.0.0.jar']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon packageUberJarForCurrentOS
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/compose/jars/${{ matrix.jar }}
